name = "borashv"
compatibility_date = "2025-11-10"

[[d1_databases]]
binding = "DB"
database_name = "borashv"
database_id = "aab88036-a0f4-4ee0-b5d3-8b96b5227c03"
#preview_database_id = "preview-database-id"
migrations_dir = "migrations"
#remote = true

[[r2_buckets]]
binding = "FILES"
bucket_name = "borashv"
#preview_bucket_name = "borashv-dev"
remote = true
